### ISSUE TITLE
need help with bui in mysql 

### ISSUE THREAD

**Issue by Visal2008** [GitTeaching/LMS-Arduino-Python#1]
@GitTeaching 

I am facing a problem where i couldn't open update book. when I press update book I receive an error
 `Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.8/tkinter/__init__.py", line 1892, in __call__
    return self.func(*args)
  File "/home/kite/Documents/Sub dist Science fair/LMS-Arduino-Python-master/app.py", line 37, in <lambda>
    update_btn['command'] = lambda: update_book(connection, row[1])
  File "/home/kite/Documents/Sub dist Science fair/LMS-Arduino-Python-master/update_book.py", line 57, in update_book
    cursor.execute(query, (bui,))
NameError: name 'bui' is not defined`

And getting this.

![Screenshot from 2023-09-15 13-34-48](https://github.com/GitTeaching/LMS-Arduino-Python/assets/145096641/c9f6eedf-811c-478c-a6fc-e608f90d3d6f)
I need your assistance as soon as possible. I am using this project for my science fair.

Hoping for your reply soon.

**Comment by GitTeaching** [comment]
- In cursor.execute(query, (bui,)), It's **bid** not **bui**.

- Also, make sure you have the same columns names in MySQL tables. 

- Also, try to put **bid** between **' '** , like this :  
   query = """select * from Book where **'bid'** = %s"""

Hope it helps.

**Comment by Visal2008** [comment]
Thank You. But I am also facing an other problem now,
`Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.8/tkinter/__init__.py", line 1892, in __call__
    return self.func(*args)
  File "/home/kite/Documents/Sub dist Science fair/LMS-Arduino-Python-master/app.py", line 37, in <lambda>
    update_btn['command'] = lambda: update_book(connection, row[0])
  File "/home/kite/Documents/Sub dist Science fair/LMS-Arduino-Python-master/update_book.py", line 73, in update_book
    id_entry.insert(0, rfid_id)
UnboundLocalError: local variable 'rfid_id' referenced before assignment`

I searched for a solution for this all over the internet but I am still not able to resolve this problem.

**Comment by GitTeaching** [comment]
It says that 'rfid_id' is referenced before assignment, meaning that 'rfid_id'  is called and used without having any value.

The reason is probably that 'record' is empty (None), i.e. **there is no book with that bid in your Book table**. So you're trying to update a book that does not exist in the database. 

You can edit the code in update_book.py to add initialization before, to see if it's empy, like this : 

**rfid_id = ' '**  //same for title, authors and desc

if record :
   for row in record:
      rfid_id = row[1]
      title = row[2]
      authors = row[3]
     descr = row[4]
   cursor.close()

Or do the same in an else block.

You'll have no value in your Entry, but you can add the book as a new one.

**Comment by Visal2008** [comment]
Thank You for your help. Without you we could have never finished this project. Because of you we are back on track. 
I am showing my extreme gratitude towards you. Thank You

**Comment by GitTeaching** [comment]
You're welcome. Really glad I could help. Wish you all the best and good luck with your project.
